### ISSUE TITLE
Bpp is high when training on the Dior dataset

### ISSUE THREAD

**Issue by YuKDseele** [shao15xiang/HL-RSCompNet#1]
I faced a problem when training the code with the Dior dataset. 
I used a batch size of 8 and an official training set(consisting of  5862 RGB images ), and the value of λ was set to 8192 (default), other parameters were kept at their default values. During training, the bpp started with a high value(around 4-8). 
<img width="367" alt="training" src="https://github.com/shao15xiang/HL-RSCompNet/assets/114339354/0f4e1b40-f83c-4c7e-9fb5-8a582852ba6e">
Even after 200 epochs, it only dropped to about 1.5, while the paper shows it should be around 0.9 for RGB datasets(GE dataset) with these settings.
Is there any problem with this？
training in pytorch 1.8.1+cu111, torchvision 0.9.1+cu111, GTX3090, ubuntu18.04.06 LST, use the DDP to accelerate training

**Comment by shao15xiang** [comment]
> I faced a problem when training the code with the Dior dataset. I used a batch size of 8 and an official training set(consisting of 5862 RGB images ), and the value of λ was set to 8192 (default), other parameters were kept at their default values. During training, the bpp started with a high value(around 4-8). <img alt="training" width="367" src="https://private-user-images.githubusercontent.com/114339354/316210410-0f4e1b40-f83c-4c7e-9fb5-8a582852ba6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODIxNTYsIm5iZiI6MTcxMTE4MTg1NiwicGF0aCI6Ii8xMTQzMzkzNTQvMzE2MjEwNDEwLTBmNGUxYjQwLWY4M2MtNGM3ZS05ZmI1LThhNTgyODUyYmE2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwODE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWFiNjliYThmZTVjZTEzZjk2YmJkODBkMzBjOWI5MWE1ZmQ5ODA5YzRkODlkNzM4MjU1NjUyMTc4ODgxYTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lsFzGsiJ_ko4zVtuR5AIDZ3KqWI2FGN0I7EVOgYnWZY"> Even after 200 epochs, it only dropped to about 1.5, while the paper shows it should be around 0.9 for RGB datasets(GE dataset) with these settings. Is there any problem with this？ training in pytorch 1.8.1+cu111, torchvision 0.9.1+cu111, GTX3090, ubuntu18.04.06 LST, use the DDP to accelerate training

The rate-distortion performance depends on the data set, sometimes the SNR is very low, and it is difficult to compress to a suitable bit rate. You can test with a dataset with a high SNR. In addition, pre-trained models can also improve the training performance of the model.
